/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 modified_honda_civic.glb 
Author: BRO (https://sketchfab.com/musawork786)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modified-honda-civic-720e9dac28214394b69874cc4641b6df
Title: Modified Honda Civic
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { OrbitControls } from "https://threejs.org/examples/jsm/controls/OrbitControls.js";


export default function Model(props) {
  const { nodes, materials } = useGLTF('/modified_honda_civic.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-78.047, 33.521, 131.254]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.FK8WheelFtR_FK8BlackGloss_0.geometry} material={materials['FK8.BlackGloss']} />
          <mesh geometry={nodes.FK8WheelFtR_FK8Red_0.geometry} material={materials['FK8.Red']} />
          <mesh geometry={nodes.FK8WheelFtR_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
          <mesh geometry={nodes.FK8WheelFtR_FK8Tire_0.geometry} material={materials['FK8.Tire']} />
          <mesh geometry={nodes.FK8WheelFtR_FK8BrakeDisc_0.geometry} material={materials['FK8.BrakeDisc']} />
          <mesh geometry={nodes.FK8WheelFtR_FK8Brown_0.geometry} material={materials['FK8.Brown']} />
        </group>
        <group position={[78.047, 33.521, 131.254]}>
          <mesh geometry={nodes.FK8WheelFtL_FK8BlackGloss_0.geometry} material={materials['FK8.BlackGloss']} />
          <mesh geometry={nodes.FK8WheelFtL_FK8Red_0.geometry} material={materials['FK8.Red']} />
          <mesh geometry={nodes.FK8WheelFtL_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
          <mesh geometry={nodes.FK8WheelFtL_FK8Tire_0.geometry} material={materials['FK8.Tire']} />
          <mesh geometry={nodes.FK8WheelFtL_FK8BrakeDisc_0.geometry} material={materials['FK8.BrakeDisc']} />
          <mesh geometry={nodes.FK8WheelFtL_FK8Brown_0.geometry} material={materials['FK8.Brown']} />
        </group>
        <group position={[-78.047, 33.521, -127.12]} scale={[-1, 1, 1]}>
          <mesh geometry={nodes.FK8WheelBkR_FK8BlackGloss_0.geometry} material={materials['FK8.BlackGloss']} />
          <mesh geometry={nodes.FK8WheelBkR_FK8Red_0.geometry} material={materials['FK8.Red']} />
          <mesh geometry={nodes.FK8WheelBkR_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
          <mesh geometry={nodes.FK8WheelBkR_FK8Tire_0.geometry} material={materials['FK8.Tire']} />
          <mesh geometry={nodes.FK8WheelBkR_FK8BrakeDisc_0.geometry} material={materials['FK8.BrakeDisc']} />
          <mesh geometry={nodes.FK8WheelBkR_FK8Brown_0.geometry} material={materials['FK8.Brown']} />
        </group>
        <group position={[78.047, 33.521, -127.12]}>
          <mesh geometry={nodes.FK8WheelBkL_FK8BlackGloss_0.geometry} material={materials['FK8.BlackGloss']} />
          <mesh geometry={nodes.FK8WheelBkL_FK8Red_0.geometry} material={materials['FK8.Red']} />
          <mesh geometry={nodes.FK8WheelBkL_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
          <mesh geometry={nodes.FK8WheelBkL_FK8Tire_0.geometry} material={materials['FK8.Tire']} />
          <mesh geometry={nodes.FK8WheelBkL_FK8BrakeDisc_0.geometry} material={materials['FK8.BrakeDisc']} />
          <mesh geometry={nodes.FK8WheelBkL_FK8Brown_0.geometry} material={materials['FK8.Brown']} />
        </group>
        <group position={[-68.554, 90.236, -181.482]}>
          <mesh geometry={nodes.FK8TaillightR_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8TaillightR_FK8Taillight_0.geometry} material={materials['FK8.Taillight']} />
          <mesh geometry={nodes.FK8TaillightR_FK8ReverseLight_0.geometry} material={materials['FK8.ReverseLight']} />
          <mesh geometry={nodes.FK8TaillightR_FK8Brakelight_0.geometry} material={materials['FK8.Brakelight']} />
          <mesh geometry={nodes.FK8TaillightR_FK8SignalR_0.geometry} material={materials['FK8.Signal.R']} />
        </group>
        <group position={[68.543, 90.218, -181.493]}>
          <mesh geometry={nodes.FK8TaillightL_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8TaillightL_FK8Taillight_0.geometry} material={materials['FK8.Taillight']} />
          <mesh geometry={nodes.FK8TaillightL_FK8SignalL_0.geometry} material={materials['FK8.Signal.L']} />
          <mesh geometry={nodes.FK8TaillightL_FK8ReverseLight_0.geometry} material={materials['FK8.ReverseLight']} />
          <mesh geometry={nodes.FK8TaillightL_FK8Brakelight_0.geometry} material={materials['FK8.Brakelight']} />
        </group>
        <group position={[1.06, 102.578, -173.593]}>
          <mesh geometry={nodes.FK8Tailgate_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8Tailgate_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8Tailgate_FK8Interior_0.geometry} material={materials['FK8.Interior']} />
          <mesh geometry={nodes.FK8Tailgate_FK8Badge_0.geometry} material={materials['FK8.Badge']} />
          <mesh geometry={nodes.FK8Tailgate_FK8Windshield_0.geometry} material={materials['FK8.Windshield']} />
          <mesh geometry={nodes.FK8Tailgate_FK8Taillight_0.geometry} material={materials['FK8.Taillight']} />
          <mesh geometry={nodes.FK8Tailgate_FK8Brakelight_0.geometry} material={materials['FK8.Brakelight']} />
          <mesh geometry={nodes.FK8Tailgate_FK8Headlight_0.geometry} material={materials['FK8.Headlight']} />
        </group>
        <group position={[35.602, 85.973, 40.124]} rotation={[-1.213, 0, 0]}>
          <mesh geometry={nodes.Fk8Steer_FK8Interior_0.geometry} material={materials['FK8.Interior']} />
          <mesh geometry={nodes.Fk8Steer_FK8Badge_0.geometry} material={materials['FK8.Badge']} />
        </group>
        <group position={[-0.046, 121.966, -186.375]}>
          <mesh geometry={nodes.FK8Spoiler_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8Spoiler_FK8BlackGloss_0.geometry} material={materials['FK8.BlackGloss']} />
        </group>
        <group position={[-3.189, 88.317, 145.371]}>
          <mesh geometry={nodes.FK8Hood_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8Hood_FK8Engine_0.geometry} material={materials['FK8.Engine']} />
          <mesh geometry={nodes.FK8Hood_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.FK8Hood_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8Hood_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
        </group>
        <group position={[-59.816, 68.543, 186.193]}>
          <mesh geometry={nodes.FK8HeadlightR_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8HeadlightR_FK8SignalR_0.geometry} material={materials['FK8.Signal.R']} />
          <mesh geometry={nodes.FK8HeadlightR_FK8RunningLight_0.geometry} material={materials['FK8.RunningLight']} />
          <mesh geometry={nodes.FK8HeadlightR_FK8Headlight_0.geometry} material={materials['FK8.Headlight']} />
          <mesh geometry={nodes.FK8HeadlightR_FK8HighBeam_0.geometry} material={materials['FK8.HighBeam']} />
        </group>
        <group position={[59.816, 68.543, 186.193]}>
          <mesh geometry={nodes.FK8HeadlightL_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8HeadlightL_FK8SignalL_0.geometry} material={materials['FK8.Signal.L']} />
          <mesh geometry={nodes.FK8HeadlightL_FK8RunningLight_0.geometry} material={materials['FK8.RunningLight']} />
          <mesh geometry={nodes.FK8HeadlightL_FK8Headlight_0.geometry} material={materials['FK8.Headlight']} />
          <mesh geometry={nodes.FK8HeadlightL_FK8HighBeam_0.geometry} material={materials['FK8.HighBeam']} />
        </group>
        <group position={[-85.75, 66.822, 101.322]}>
          <mesh geometry={nodes.FK8FenderR_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8FenderR_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8FenderR_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
        </group>
        <group position={[85.75, 66.822, 101.322]}>
          <mesh geometry={nodes.FK8FenderL_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8FenderL_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8FenderL_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
        </group>
        <group position={[-75.679, 85.646, 36.169]}>
          <mesh geometry={nodes.FK8DoorFtR_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8DoorFtR_FK8Interior_0.geometry} material={materials['FK8.Interior']} />
          <mesh geometry={nodes.FK8DoorFtR_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8DoorFtR_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
          <mesh geometry={nodes.FK8DoorFtR_FK8Windshield_0.geometry} material={materials['FK8.Windshield']} />
          <mesh geometry={nodes.FK8DoorFtR_Material002_0.geometry} material={materials['Material.002']} />
          <mesh geometry={nodes.FK8DoorFtR_FK8Carbon_0.geometry} material={materials['FK8.Carbon']} />
          <mesh geometry={nodes.FK8DoorFtR_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
        </group>
        <group position={[75.862, 85.462, 35.784]}>
          <mesh geometry={nodes.FK8DoorFtL_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8DoorFtL_FK8Interior_0.geometry} material={materials['FK8.Interior']} />
          <mesh geometry={nodes.FK8DoorFtL_Material004_0.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.FK8DoorFtL_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8DoorFtL_FK8Windshield_0.geometry} material={materials['FK8.Windshield']} />
          <mesh geometry={nodes.FK8DoorFtL_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
          <mesh geometry={nodes.FK8DoorFtL_FK8Carbon_0.geometry} material={materials['FK8.Carbon']} />
          <mesh geometry={nodes.FK8DoorFtL_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
        </group>
        <group position={[-73.267, 85.054, -61.456]}>
          <mesh geometry={nodes.FK8DoorBkR_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8DoorBkR_FK8Interior_0.geometry} material={materials['FK8.Interior']} />
          <mesh geometry={nodes.FK8DoorBkR_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8DoorBkR_FK8Windshield_0.geometry} material={materials['FK8.Windshield']} />
          <mesh geometry={nodes.FK8DoorBkR_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.FK8DoorBkR_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
        </group>
        <group position={[73.254, 84.843, -61.426]}>
          <mesh geometry={nodes.FK8DoorBkL_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8DoorBkL_FK8Interior_0.geometry} material={materials['FK8.Interior']} />
          <mesh geometry={nodes.FK8DoorBkL_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8DoorBkL_FK8Windshield_0.geometry} material={materials['FK8.Windshield']} />
          <mesh geometry={nodes.FK8DoorBkL_Material005_0.geometry} material={materials['Material.005']} />
          <mesh geometry={nodes.FK8DoorBkL_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
        </group>
        <group position={[0.656, 47.766, 199.572]}>
          <mesh geometry={nodes.FK8BumperFt_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8BumperFt_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8BumperFt_FK8Carbon_0.geometry} material={materials['FK8.Carbon']} />
          <mesh geometry={nodes.FK8BumperFt_FK8Badge_0.geometry} material={materials['FK8.Badge']} />
          <mesh geometry={nodes.FK8BumperFt_FK8RedGloss_0.geometry} material={materials['FK8.RedGloss']} />
          <mesh geometry={nodes.FK8BumperFt_FK8HeadlightGlass_0.geometry} material={materials['FK8.HeadlightGlass']} />
          <mesh geometry={nodes.FK8BumperFt_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
          <mesh geometry={nodes.FK8BumperFt_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
          <mesh geometry={nodes.FK8BumperFt_FK8Headlight_0.geometry} material={materials['FK8.Headlight']} />
          <mesh geometry={nodes.FK8BumperFt_FK8HighBeam_0.geometry} material={materials['FK8.HighBeam']} />
        </group>
        <group position={[0.058, 46.828, -197.483]}>
          <mesh geometry={nodes.FK8BumperBk_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.FK8BumperBk_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.FK8BumperBk_FK8Carbon_0.geometry} material={materials['FK8.Carbon']} />
          <mesh geometry={nodes.FK8BumperBk_FK8RedGloss_0.geometry} material={materials['FK8.RedGloss']} />
          <mesh geometry={nodes.FK8BumperBk_FK8HeadlightGlass_0.geometry} material={materials['FK8.HeadlightGlass']} />
          <mesh geometry={nodes.FK8BumperBk_FK8Gray_0.geometry} material={materials['FK8.Gray']} />
          <mesh geometry={nodes.FK8BumperBk_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
          <mesh geometry={nodes.FK8BumperBk_FK8Brakelight_0.geometry} material={materials['FK8.Brakelight']} />
        </group>
        <group position={[1.676, 80.72, 51.613]}>
          <mesh geometry={nodes.Fk8Body_FK8Paint_0.geometry} material={materials['FK8.Paint']} />
          <mesh geometry={nodes.Fk8Body_FK8Interior_0.geometry} material={materials['FK8.Interior']} />
          <mesh geometry={nodes.Fk8Body_FK8Engine_0.geometry} material={materials['FK8.Engine']} />
          <mesh geometry={nodes.Fk8Body_FK8Carbon_0.geometry} material={materials['FK8.Carbon']} />
          <mesh geometry={nodes.Fk8Body_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} />
          <mesh geometry={nodes.Fk8Body_FK8Badge_0.geometry} material={materials['FK8.Badge']} />
          <mesh geometry={nodes.Fk8Body_FK8Red_0.geometry} material={materials['FK8.Red']} />
          <mesh geometry={nodes.Fk8Body_FK8RedGloss_0.geometry} material={materials['FK8.RedGloss']} />
          <mesh geometry={nodes.Fk8Body_FK8Grille_0.geometry} material={materials['FK8.Grille']} />
          <mesh geometry={nodes.Fk8Body_FK8Interiorlights_0.geometry} material={materials['FK8.Interiorlights']} />
          <mesh geometry={nodes.Fk8Body_FK8Chrome_0.geometry} material={materials['FK8.Chrome']} />
        </group>
        <mesh geometry={nodes.FK8Wipers_FK8BlackMatt_0.geometry} material={materials['FK8.BlackMatt']} position={[-0.751, 95.093, 109.242]} />
        <mesh geometry={nodes.FK8Windshield_FK8Windshield_0.geometry} material={materials['FK8.Windshield']} position={[-0.492, 110.932, 71.405]} />
        <mesh geometry={nodes.FK8WheelBrakeFtR_FK8RedGloss_0.geometry} material={materials['FK8.RedGloss']} position={[-80.512, 32.581, 144.87]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.FK8WheelBrakeFtL_FK8RedGloss_0.geometry} material={materials['FK8.RedGloss']} position={[80.512, 32.581, 144.87]} />
        <mesh geometry={nodes.FK8WheelBrakeBkR_FK8RedGloss_0.geometry} material={materials['FK8.RedGloss']} position={[-77.901, 39.944, -143.796]} scale={[-1, 1, 1]} />
        <mesh geometry={nodes.FK8WheelBrakeBkL_FK8RedGloss_0.geometry} material={materials['FK8.RedGloss']} position={[77.901, 39.944, -143.796]} />
        <mesh geometry={nodes.FK8TaillightGlassR_FK8HeadlightGlass_0.geometry} material={materials['FK8.HeadlightGlass']} position={[-69.55, 91.909, -181.111]} />
        <mesh geometry={nodes.FK8TaillightGlassL_FK8HeadlightGlass_0.geometry} material={materials['FK8.HeadlightGlass']} position={[69.55, 91.909, -181.111]} />
        <mesh geometry={nodes.FK8TailgateGlass_FK8Windshield_0.geometry} material={materials['FK8.Windshield']} position={[0, 112.396, -171.032]} />
        <mesh geometry={nodes.FK8NeedleTacho_FK8Interiorlights_0.geometry} material={materials['FK8.Interiorlights']} position={[41.123, 87.18, 64.439]} rotation={[-0.794, 0, 0]} />
        <mesh geometry={nodes.FK8HeadlightGlassR_FK8HeadlightGlass_0.geometry} material={materials['FK8.HeadlightGlass']} position={[-62.717, 69.453, 188.498]} />
        <mesh geometry={nodes.FK8HeadlightGlassL_FK8HeadlightGlass_0.geometry} material={materials['FK8.HeadlightGlass']} position={[62.717, 69.453, 188.498]} />
      </group>
    </group>
  )
}

useGLTF.preload('/modified_honda_civic.glb')
